apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-dbconnect
  labels:
    sretraining: lamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-dbconnect
  template:
    metadata:
      labels:
        app: php-dbconnect
    spec:
      containers:
      - name: php-dbconnect
        image: heptio/example-php-dbconnect
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: MYSQL_HOST
          value: mysql.default.svc.cluster.local
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    sretraining: lamp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php-dbconnect

