apiVersion: v1
kind: Service
metadata:
  name: webapp-blue-green
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
    version: "1.17"
  type: LoadBalancer
